### ISSUE TITLE
Replica resolution

### ISSUE THREAD

**Issue by tberriel** [opennerf/opennerf#11]
Hi, first of all thanks for publishing the code, it's really useful!

I had a question about the resolution used to train on Replica dataset. The paper states that images are scaled to 640x320 pixels. Nevertheless, this resolution does not correspond to any of the generated from the preprocessing script, which are all downscaling of  1200x680 keeping the image ratio. 
Did you use an additional preprocessing step changing the image ratio?
Thanks!

Tomás

**Comment by francisengelmann** [comment]
The code provided here is a reimplementation for nerfstudio. There might be small differences (like this one) between the paper and this code. The scores of the method, however, are comparable to the ones published in the paper (see Readme.md).

**Comment by tberriel** [comment]
Okay, thanks!
