### ISSUE TITLE
LERF relevancy rendering implementation

### ISSUE THREAD

**Issue by laliwang** [opennerf/opennerf#2]
Thanks for your great works! And I just wonder how do you render the relevancy maps in LERF since they don't open this until today. Thanks a lot if you have any insight!

**Comment by francisengelmann** [comment]
You can directly retrieve the relevancy maps from the outputs of LERF:
```
outputs = pipeline.model.get_outputs_for_camera_ray_bundle(camera_ray_bundle)
relevancies = [k for k in outputs.keys() if k.startswith('relevancy')]
```

Not the full code yet, but I hope this helps for now - let me know
