### ISSUE TITLE
Cannot see predicted semantics in Nerfstudio visualization

### ISSUE THREAD

**Issue by lusxvr** [opennerf/opennerf#7]
After I run all the skripts to train and evaluate a scene and open the visualization in the nerfstudio viewer, I can only toggle the controls `colors`, `semantics_gt`, `axis`. 
After the training and evaluation step in the `viz` directory I have both the `semantics_gt.bin` and the `semantics_pr.bin` so I am wondering why I cannot see them in the visualisation. 
I hope this is the right place to ask this question because I figured you might have seen this issue before since there are some visualisations of the predictions in the paper

**Comment by francisengelmann** [comment]
The semantics are not visualized in nerfstudio, instead you can look at them in the browser - cd into the dir containing the semantics_gt.bin and type `python -m http.server`, then (in your browser) navigate to the indicated address, i.e., https://localhost:8000 - does that work?

**Comment by lusxvr** [comment]
Yes, this is exactly what I did but they dont appear unfortunately

**Comment by francisengelmann** [comment]
Could you post a screenshot of your browser when navigating to https://localhost:8000/ ?

**Comment by lusxvr** [comment]
After trying it again today it worked as expected, I guess I just did something wrong yesterday, thanks for the help though!
